# Execute the code below

In [2]:
import pandas as pd
import numpy as np
link = "https://raw.githubusercontent.com/WildCodeSchool/data-training-resources/main/quests/weather2019.csv"
df_weather = pd.read_csv(link)

In [ ]:
#columns = colonnes
#index = lignes
#values = valeurs
#aggfunc = fonction d'agr√©gation

# You have now a DataFrame with lots of weather data

In [ ]:
df_weather.head()

         DATE  MAX_TEMPERATURE_C  MIN_TEMPERATURE_C  ...   OPINION  MONTH  DAY
0  2019-01-01                  9                  4  ...  very bad      1    1
1  2019-01-02                  8                  5  ...  very bad      1    2
2  2019-01-03                  6                  0  ...  very bad      1    3
3  2019-01-04                  5                 -1  ...  very bad      1    4
4  2019-01-05                  6                 -1  ...  very bad      1    5

[5 rows x 24 columns]

# PIVOT TABLE

## It's like in Excel, but with Pandas

There are 2 syntaxes, choose your preferred :
- As a method : YOUR_DATAFRAME.pivot_table()
- As a function : pd.crosstab()

In [3]:
df_weather.describe()

,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,TEMPERATURE_MORNING_C,TEMPERATURE_NOON_C,TEMPERATURE_EVENING_C,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,VISIBILITY_AVG_KM,PRESSURE_MAX_MB,...,DEWPOINT_MAX_C,WINDTEMP_MAX_C,WEATHER_CODE_MORNING,WEATHER_CODE_NOON,WEATHER_CODE_EVENING,TOTAL_SNOW_MM,UV_INDEX,SUNHOUR,MONTH,DAY
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.0,365.000000,365.000000,365.000000,365.000000
mean,16.810959,9.095890,19.624658,10.106849,15.487671,14.958904,3.015890,80.095890,9.428767,1019.038356,...,10.945205,10.989041,168.512329,164.419178,181.638356,0.0,1.380822,9.315890,6.526027,15.720548
std,6.712698,4.814026,8.151987,5.128254,6.565644,6.789290,5.697129,10.413649,2.221039,9.114272,...,4.190159,6.980341,77.739513,78.205120,86.458436,0.0,1.279665,3.608357,3.452584,8.808321
min,5.000000,-1.000000,3.000000,-1.000000,0.000000,0.000000,0.000000,41.000000,5.000000,987.000000,...,1.000000,-4.000000,113.000000,113.000000,113.000000,0.0,1.000000,3.300000,1.000000,1.000000
25%,11.000000,5.000000,14.000000,6.000000,11.000000,10.000000,0.000000,75.000000,8.250000,1014.000000,...,8.000000,5.000000,116.000000,116.000000,116.000000,0.0,1.000000,6.500000,4.000000,8.000000
50%,16.000000,9.000000,18.000000,10.000000,15.000000,14.000000,0.700000,82.000000,9.500000,1020.000000,...,11.000000,10.000000,122.000000,119.000000,122.000000,0.0,1.000000,9.300000,7.000000,16.000000
75%,21.000000,13.000000,25.000000,14.000000,20.000000,19.000000,3.800000,88.000000,10.000000,1024.000000,...,14.000000,17.000000,176.000000,176.000000,176.000000,0.0,1.000000,11.600000,10.000000,23.000000
max,39.000000,25.000000,46.000000,25.000000,36.000000,37.000000,47.600000,98.000000,20.000000,1040.000000,...,25.000000,29.000000,386.000000,353.000000,389.000000,0.0,7.000000,16.000000,12.000000,31.000000

In [6]:
valeur_nulles=df_weather.isna().count().size
print(valeur_nulles)

24

In [7]:
# Example
df_weather.pivot_table(values = 'MAX_TEMPERATURE_C', index = 'MONTH', aggfunc = 'mean')

       MAX_TEMPERATURE_C
MONTH
1               8.161290
2              12.750000
3              13.064516
4              14.900000
5              16.870968
6              22.166667
7              26.806452
8              25.290323
9              22.533333
10             16.935484
11             11.300000
12             10.677419

## Create a Pivot table with :
- Months on rows
- the maximum of Max Temperature on values
- Opinion on columns

In [9]:
# Hop !
df_weather.pivot_table(values='MAX_TEMPERATURE_C',
                       index=['MONTH', 'OPINION'], aggfunc='max')

                        MAX_TEMPERATURE_C
MONTH OPINION
1     bad                              11
      very bad                         10
2     bad                              13
      good                             20
      not good not bad                 17
      very bad                         12
3     bad                              14
      good                             19
      not good not bad                 17
      very bad                         12
4     bad                              18
      good                             24
      not good not bad                 19
      very bad                         14
5     bad                              19
      good                             25
      not good not bad                 20
      very bad                         15
6     bad                              23
      good                             32
      not good not bad                 34
      very bad                         15
      very good                        29
7     bad                              31
      good                             33
      not good not bad                 39
      very bad                         22
      very good                        33
8     bad                              24
      good                             33
      not good not bad                 30
      very good                        29
9     bad                              21
      good                             31
      not good not bad                 20
      very bad                         20
10    bad                              20
      good                             21
      not good not bad                 20
      very bad                         14
11    bad                              17
      not good not bad                 13
      very bad                         14
12    bad                              13
      not good not bad                 13
      very bad                         14

## Pivot table with :
- Days on rows
- Precipitation on values
- Months on columns

In [ ]:
# Hop !

## Pivot table with :
- Months on rows
- the sum of Precipitations on values

**Then display it as a column chart.** (optionnal)

In [ ]:
# Hop !

## Pivot table with :
- Months on rows
- the average of Max Temperature on a first column of values
- the average of Sunhours on a second column of values

In [ ]:
# Hop !

# Chart
Using your favorite library (MatPlotLib, Seaborn, Plotly or what you want), draw a chart from the previous pivot table with :
- Temperature in a blue column chart
- Sunhours in a red line plot

Tip : Once your pivot table created, you can help yourself with the `.reset_index()`  method.

In [ ]:
# Your code here