# Mission 1

![](https://i.imgur.com/Ax3pp2A.png)


Create a "fruit" dataframe that reflects the above example **using a list** data structure

[This resource could help you](https://datatofish.com/list-to-dataframe/).

# Mission 2

Create a "fruit_vendors" dataframe that reflects the below example **using a dictionary** data structure

![](https://i.imgur.com/CHPn7ZF.png)

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)

# Mission 3

Use a loop to display the values from each column in the dataframe from mission 2.

# Mission 4

Delete the first row of the dataframe from mission 2

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)

# Mission 5

Delete the first column from the dataframe from mission 2.