In [3]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors

In [4]:
poke = pd.read_csv('https://raw.githubusercontent.com/murpi/wilddata/master/pokemon.csv', index_col=0)
poke.head()

            Name Type 1  Type 2  HP  ...  Sp. Def  Speed  Generation  Legendary
#                                    ...
1      Bulbasaur  Grass  Poison  45  ...       65     45           1      False
2        Ivysaur  Grass  Poison  60  ...       80     60           1      False
3       Venusaur  Grass  Poison  80  ...      100     80           1      False
4  Mega Venusaur  Grass  Poison  80  ...      120     80           1      False
5     Charmander   Fire     NaN  39  ...       50     65           1      False

[5 rows x 11 columns]

In [31]:
# dataframe X avec les valeurs numériques des pokémon non légendaires
poke_sans_legendaires = poke[poke['Legendary'] == False]
X = poke_sans_legendaires[['HP', 	'Attack', 	'Defense',	'Sp. Atk', 	'Sp. Def', 	'Speed']]
X

     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
#
1    45      49       49       65       65     45
2    60      62       63       80       80     60
3    80      82       83      100      100     80
4    80     100      123      122      120     80
5    39      52       43       60       50     65
..   ..     ...      ...      ...      ...    ...
788  85     100      122       58       75     54
789  55      69       85       32       35     28
790  95     117      184       44       46     28
791  40      30       35       45       40     55
792  85      70       80       97       80    123

[735 rows x 6 columns]

In [33]:
#entrainement du modèle
distanceKNN = NearestNeighbors(n_neighbors=2).fit(X)

In [32]:
#affichage des paramètres des pokemon à remplacer
mes_légendaires = poke[(poke['Name'] == 'Mewtwo') | (poke['Name'] == 'Lugia') | (poke['Name'] == 'Rayquaza') | (poke['Name'].str.contains('Giratina')) | (poke['Name'] == 'Dialga') | (poke['Name'] ==  'Palkia')]
mes_légendaires

                       Name   Type 1  Type 2  ...  Speed  Generation  Legendary
#                                             ...
163                  Mewtwo  Psychic     NaN  ...    130           1       True
270                   Lugia  Psychic  Flying  ...    110           2       True
426                Rayquaza   Dragon  Flying  ...     95           3       True
541                  Dialga    Steel  Dragon  ...     90           4       True
542                  Palkia    Water  Dragon  ...    100           4       True
545  Giratina Altered Forme    Ghost  Dragon  ...     90           4       True
546   Giratina Origin Forme    Ghost  Dragon  ...     90           4       True

[7 rows x 11 columns]

In [34]:
#enregistrement des distances et voisions les plus proches dans des variables
neighMewtwo = distanceKNN.kneighbors([[106, 	110, 	90, 	154, 	90, 	130]])
neighLugia = distanceKNN.kneighbors([[106, 	90, 	130, 	90, 	154, 	110]]	)
neighRay = distanceKNN.kneighbors([[105, 	150 ,	90, 	150 ,	90 ,	95]])
neighDialga = distanceKNN.kneighbors([[100, 	120, 	120 ,	150 ,	100 ,	90]])
neighPalkia = distanceKNN.kneighbors([[90, 	120 ,	100 ,	150 ,	120 ,	100]])
neighGiratinaAlt = distanceKNN.kneighbors([[150, 	100 ,	120 ,	100 ,	120 ,	90]])
neighGiratinaOr = distanceKNN.kneighbors([[150, 	120 ,	100 ,	120 ,	100 ,	90 ]])

In [35]:
#création d'un nouveau dataframe avec les deux voisins les plus proches pour chaque pokémon, priorisés par les distances
recommendation = pd.DataFrame([ ['Mewtwo',   poke_sans_legendaires.iloc[neighMewtwo[1][0][0]]['Name'],  poke_sans_legendaires.iloc[neighMewtwo[1][0][1]]['Name']], 
                                ['Lugia',    poke_sans_legendaires.iloc[neighLugia[1][0][0]]['Name'],   poke_sans_legendaires.iloc[neighLugia[1][0][1]]['Name']],
                                ['Rayquaza', poke_sans_legendaires.iloc[neighRay[1][0][0]]['Name'],     poke_sans_legendaires.iloc[neighRay[1][0][1]]['Name']],
                                ['Dialga',   poke_sans_legendaires.iloc[neighDialga[1][0][0]]['Name'],  poke_sans_legendaires.iloc[neighDialga[1][0][1]]['Name']],
                                ['Palkia',   poke_sans_legendaires.iloc[neighPalkia[1][0][0]]['Name'],  poke_sans_legendaires.iloc[neighPalkia[1][0][1]]['Name']],
                                ['Giratina Altered Forme',   poke_sans_legendaires.iloc[neighGiratinaAlt[1][0][0]]['Name'],  poke_sans_legendaires.iloc[neighGiratinaAlt[1][0][1]]['Name']],
                                ['Giratina Origin Forme',   poke_sans_legendaires.iloc[neighGiratinaOr[1][0][0]]['Name'],  poke_sans_legendaires.iloc[neighGiratinaOr[1][0][1]]['Name']]
                               ],
                               columns = ['pokemon_à_remplacer', 'first_Choice', 'second_Choice']
                              )
recommendation

      pokemon_à_remplacer      first_Choice     second_Choice
0                  Mewtwo     Mega Houndoom     Mega Sceptile
1                   Lugia         Cresselia     Mega Venusaur
2                Rayquaza     Mega Blaziken     Mega Garchomp
3                  Dialga    Mega Blastoise  Mega Charizard X
4                  Palkia  Mega Charizard Y    Mega Blastoise
5  Giratina Altered Forme         Cresselia               Mew
6   Giratina Origin Forme            Celebi               Mew