In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/imdb_top_1000.csv")

In [ ]:
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [ ]:
df[
    [
        "Series_Title",
        "Released_Year",
        "Runtime",
        "Genre",
        "IMDB_Rating",
        "Director",
        "Star1",
        "Star2",
        "Star3",
        "Star4",
        "No_of_Votes",
        "Gross",
    ]
].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Runtime        1000 non-null   object
 3   Genre          1000 non-null   object
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   object
 6   Star1          1000 non-null   object
 7   Star2          1000 non-null   object
 8   Star3          1000 non-null   object
 9   Star4          1000 non-null   object
 10  No_of_Votes    1000 non-null   int64
 11  Gross          831 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 93.9+ KB

In [ ]:
df = (
    df[
        [
            "Series_Title",
            "Released_Year",
            "Runtime",
            "Genre",
            "IMDB_Rating",
            "Director",
            "Star1",
            "Star2",
            "Star3",
            "Star4",
            "No_of_Votes",
            "Gross",
        ]
    ]
    .dropna()
    .reset_index(drop=True)
)

In [ ]:
df.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,142 min,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,1972,175 min,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,1974,202 min,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,12 Angry Men,1957,96 min,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 831 entries, 0 to 830
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   831 non-null    object
 1   Released_Year  831 non-null    object
 2   Runtime        831 non-null    object
 3   Genre          831 non-null    object
 4   IMDB_Rating    831 non-null    float64
 5   Director       831 non-null    object
 6   Star1          831 non-null    object
 7   Star2          831 non-null    object
 8   Star3          831 non-null    object
 9   Star4          831 non-null    object
 10  No_of_Votes    831 non-null    int64
 11  Gross          831 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 78.0+ KB

In [ ]:
df.Released_Year.astype("int")

ValueError: invalid literal for int() with base 10: 'PG'

In [ ]:
# transforme la date en int
listeReleased_Year = []
for element in df.Released_Year:
    try:
        valeur = int(element)
        listeReleased_Year.append(valeur)
    except:
        listeReleased_Year.append(np.nan)

In [ ]:
df.Runtime.str.split(" "):

0      [142, min]
1      [175, min]
2      [152, min]
3      [202, min]
4       [96, min]
          ...
826    [157, min]
827    [144, min]
828     [78, min]
829     [87, min]
830    [118, min]
Name: Runtime, Length: 831, dtype: object

In [ ]:
listeRuntime = []
for element in df.Runtime.str.split(" "):
    try:
        listeRuntime.append(element[0])
    except:
        listeRuntime.append(np.nan)

In [ ]:
df.Gross.str.replace(",", "").astype("int")

0       28341469
1      134966411
2      534858444
3       57300000
4        4360000
         ...
826       696690
827      1378435
828    141843612
829     13780024
830     30500000
Name: Gross, Length: 831, dtype: int64

In [ ]:
df["Released_Year_clean"] = listeReleased_Year
df["Runtime_Clean"] = listeRuntime
df["Gross_clean"] = df.Gross.str.replace(",", "").astype("int")

In [ ]:
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Released_Year_clean,Runtime_Clean,Gross_clean
0,The Shawshank Redemption,1994,142 min,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",1994.0,142,28341469
1,The Godfather,1972,175 min,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",1972.0,175,134966411
2,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444",2008.0,152,534858444
3,The Godfather: Part II,1974,202 min,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000",1974.0,202,57300000
4,12 Angry Men,1957,96 min,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000",1957.0,96,4360000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
826,Giù la testa,1971,157 min,"Drama, War, Western",7.6,Sergio Leone,Rod Steiger,James Coburn,Romolo Valli,Maria Monti,30144,"696,690",1971.0,157,696690
827,Kelly's Heroes,1970,144 min,"Adventure, Comedy, War",7.6,Brian G. Hutton,Clint Eastwood,Telly Savalas,Don Rickles,Carroll O'Connor,45338,"1,378,435",1970.0,144,1378435
828,The Jungle Book,1967,78 min,"Animation, Adventure, Family",7.6,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,166409,"141,843,612",1967.0,78,141843612
829,A Hard Day's Night,1964,87 min,"Comedy, Music, Musical",7.6,Richard Lester,John Lennon,Paul McCartney,George Harrison,Ringo Starr,40351,"13,780,024",1964.0,87,13780024
830,From Here to Eternity,1953,118 min,"Drama, Romance, War",7.6,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000",1953.0,118,30500000

In [ ]:
dfFinal = (
    df.drop(["Released_Year", "Runtime", "Gross"], axis=1)
    .dropna()
    .reset_index(drop=True)
)

In [ ]:
dfFinal

,Series_Title,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,No_of_Votes,Released_Year_clean,Runtime_Clean,Gross_clean
0,The Shawshank Redemption,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,1994.0,142,28341469
1,The Godfather,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,1972.0,175,134966411
2,The Dark Knight,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,2008.0,152,534858444
3,The Godfather: Part II,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,1974.0,202,57300000
4,12 Angry Men,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,1957.0,96,4360000
...,...,...,...,...,...,...,...,...,...,...,...,...
825,Giù la testa,"Drama, War, Western",7.6,Sergio Leone,Rod Steiger,James Coburn,Romolo Valli,Maria Monti,30144,1971.0,157,696690
826,Kelly's Heroes,"Adventure, Comedy, War",7.6,Brian G. Hutton,Clint Eastwood,Telly Savalas,Don Rickles,Carroll O'Connor,45338,1970.0,144,1378435
827,The Jungle Book,"Animation, Adventure, Family",7.6,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,166409,1967.0,78,141843612
828,A Hard Day's Night,"Comedy, Music, Musical",7.6,Richard Lester,John Lennon,Paul McCartney,George Harrison,Ringo Starr,40351,1964.0,87,13780024
829,From Here to Eternity,"Drama, Romance, War",7.6,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,1953.0,118,30500000

In [ ]:
pd.get_dummies(dfFinal.Genre)
pd.get_dummies(dfFinal.Director)
pd.get_dummies(dfFinal.Star1)
pd.get_dummies(dfFinal.Star2)
pd.get_dummies(dfFinal.Star3)
pd.get_dummies(dfFinal.Star4)

,Abdel Ahmed Ghili,Abigail Breslin,Adam Baldwin,Adrien Brody,Agnes Moorehead,Ahmet Mümtaz Taylan,Ahna Capri,Ahney Her,Ajay Naidu,Akihiro Miwa,...,You Ge,Yukiko Shimazaki,Yun Qu,Yvonne Furneaux,Zac Mattoon O'Brien,Zach Grenier,Ziyi Zhang,Zoe Saldana,Zoë Kravitz,Álvaro Guerrero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
826,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
827,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
828,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
829,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
dfFeatures = pd.concat(
    [
        pd.get_dummies(dfFinal.Genre),        pd.get_dummies(dfFinal.Director),        pd.get_dummies(
            dfFinal.Star1),        pd.get_dummies(dfFinal.Star2),        pd.get_dummies(dfFinal.Star3),
        pd.get_dummies(dfFinal.Star4),        dfFinal["Series_Title"],
        dfFinal["IMDB_Rating"],        dfFinal["No_of_Votes"],        dfFinal["Released_Year_clean"],        dfFinal["Runtime_Clean"],
        dfFinal["Gross_clean"],
    ],

    axis=1,
)

In [ ]:
dfFeatures

,"Action, Adventure","Action, Adventure, Comedy","Action, Adventure, Drama","Action, Adventure, Family","Action, Adventure, Fantasy","Action, Adventure, History","Action, Adventure, Horror","Action, Adventure, Mystery","Action, Adventure, Romance","Action, Adventure, Sci-Fi",...,Ziyi Zhang,Zoe Saldana,Zoë Kravitz,Álvaro Guerrero,Series_Title,IMDB_Rating,No_of_Votes,Released_Year_clean,Runtime_Clean,Gross_clean
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,The Shawshank Redemption,9.3,2343110,1994.0,142,28341469
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,The Godfather,9.2,1620367,1972.0,175,134966411
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,The Dark Knight,9.0,2303232,2008.0,152,534858444
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,The Godfather: Part II,9.0,1129952,1974.0,202,57300000
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,12 Angry Men,9.0,689845,1957.0,96,4360000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,Giù la testa,7.6,30144,1971.0,157,696690
826,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,Kelly's Heroes,7.6,45338,1970.0,144,1378435
827,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,The Jungle Book,7.6,166409,1967.0,78,141843612
828,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,A Hard Day's Night,7.6,40351,1964.0,87,13780024
829,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,From Here to Eternity,7.6,43374,1953.0,118,30500000

In [ ]:
from sklearn.neighbors import NearestNeighbors

In [ ]:
neigh = NearestNeighbors(n_neighbors=15)

In [ ]:
neigh.fit(dfFeatures.drop("Series_Title", axis=1).values)

NearestNeighbors(n_neighbors=15)

In [ ]:
dfFeatures.Series_Title

0      The Shawshank Redemption
1                 The Godfather
2               The Dark Knight
3        The Godfather: Part II
4                  12 Angry Men
                 ...
825                Giù la testa
826              Kelly's Heroes
827             The Jungle Book
828          A Hard Day's Night
829       From Here to Eternity
Name: Series_Title, Length: 830, dtype: object

In [ ]:
# modele knn voisin les plus proches
distances, index = neigh.kneighbors(dfFeatures.drop("Series_Title", axis=1).values[0].reshape(1, -1)
)

In [ ]:
distances

array([[      0.        , 1620395.78832515, 2152108.81065953,
        2168852.20724506, 2270573.41929839, 2311903.74016469,
        2364750.7594166 , 2390132.26806797, 2433008.45719774,
        2525966.4115058 , 2526655.20943062, 2600488.44232867,
        2667275.10038269, 2685965.05709985, 2770138.95546719]])

In [ ]:
index

array([[  0,  95, 237, 293, 533, 713, 180, 334, 350, 680,  81, 738, 705,
        555, 451]])

In [91]:
dfFeatures.Series_Title.iloc[index[0]].values

array(['The Shawshank Redemption', 'Taxi Driver', 'Chinatown',
       'Dallas Buyers Club', 'The Insider', 'A Man for All Seasons',
       'Rush', 'Do the Right Thing', 'The Last Picture Show',
       'The Muppet Christmas Carol', 'Snatch', 'Hell or High Water',
       'Serpico', 'Glory', 'Spartacus'], dtype=object)

In [ ]:
df.iloc[index[0]]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Released_Year_clean,Runtime_Clean,Gross_clean
0,The Shawshank Redemption,1994,142 min,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",1994.0,142,28341469
95,Taxi Driver,1976,114 min,"Crime, Drama",8.3,Martin Scorsese,Robert De Niro,Jodie Foster,Cybill Shepherd,Albert Brooks,724636,"28,262,574",1976.0,114,28262574
237,Chinatown,1974,130 min,"Drama, Mystery, Thriller",8.1,Roman Polanski,Jack Nicholson,Faye Dunaway,John Huston,Perry Lopez,294230,"29,000,000",1974.0,130,29000000
293,Dallas Buyers Club,2013,117 min,"Biography, Drama",8.0,Jean-Marc Vallée,Matthew McConaughey,Jennifer Garner,Jared Leto,Steve Zahn,441614,"27,298,285",2013.0,117,27298285
533,The Insider,1999,157 min,"Biography, Drama, Thriller",7.8,Michael Mann,Russell Crowe,Al Pacino,Christopher Plummer,Diane Venora,159886,"28,965,197",1999.0,157,28965197
713,A Man for All Seasons,1966,120 min,"Biography, Drama, History",7.7,Fred Zinnemann,Paul Scofield,Wendy Hiller,Robert Shaw,Leo McKern,31222,"28,350,000",1966.0,120,28350000
180,Rush,2013,123 min,"Action, Biography, Drama",8.1,Ron Howard,Daniel Brühl,Chris Hemsworth,Olivia Wilde,Alexandra Maria Lara,432811,"26,947,624",2013.0,123,26947624
334,Do the Right Thing,1989,120 min,"Comedy, Drama",8.0,Spike Lee,Danny Aiello,Ossie Davis,Ruby Dee,Richard Edson,89429,"27,545,445",1989.0,120,27545445
350,The Last Picture Show,1971,118 min,"Drama, Romance",8.0,Peter Bogdanovich,Timothy Bottoms,Jeff Bridges,Cybill Shepherd,Ben Johnson,42456,"29,133,000",1971.0,118,29133000
680,The Muppet Christmas Carol,1992,85 min,"Comedy, Drama, Family",7.7,Brian Henson,Michael Caine,Kermit the Frog,Dave Goelz,Miss Piggy,50298,"27,281,507",1992.0,85,27281507
81,Snatch,2000,104 min,"Comedy, Crime",8.3,Guy Ritchie,Jason Statham,Brad Pitt,Benicio Del Toro,Dennis Farina,782001,"30,328,156",2000.0,104,30328156
738,Hell or High Water,2016,102 min,"Action, Crime, Drama",7.6,David Mackenzie,Chris Pine,Ben Foster,Jeff Bridges,Gil Birmingham,204175,"26,862,450",2016.0,102,26862450
705,Serpico,1973,130 min,"Biography, Crime, Drama",7.7,Sidney Lumet,Al Pacino,John Randolph,Jack Kehoe,Biff McGuire,109941,"29,800,000",1973.0,130,29800000
555,Glory,1989,122 min,"Biography, Drama, History",7.8,Edward Zwick,Matthew Broderick,Denzel Washington,Cary Elwes,Morgan Freeman,122779,"26,830,000",1989.0,122,26830000
451,Spartacus,1960,197 min,"Adventure, Biography, Drama",7.9,Stanley Kubrick,Kirk Douglas,Laurence Olivier,Jean Simmons,Charles Laughton,124339,"30,000,000",1960.0,197,30000000

In [96]:
neigh

NearestNeighbors(n_neighbors=15)

In [ ]:
from joblib import dump, load

In [83]:
dump(neigh, "recoNetflox2.joblib")

['recoNetflox2.joblib']

In [ ]:
import pickle

In [82]:
s = pickle.dumps(neigh)

In [ ]:
dfFeatures.to_csv("dfFeatures.csv", index=False)

In [ ]:
dfFeatures[dfFeatures.Series_Title == "Captain America: The Winter Soldier"].index[0]